### ISSUE TITLE
Linux 5.7: "use of undeclared identifier 'KBUILD_MODNAME'"

### ISSUE THREAD

**Issue by sanderjo** [mechpen/sockdump#4]
On Ubuntu 20.04 with Linux 5.7.0, I get the errors below.

Might be related to

- https://github.com/iovisor/bpftrace/issues/715
- https://github.com/falcosecurity/falco/issues/1334
- https://github.com/redsift/redbpf/issues/71

It might also be a PEBKAC, or wrong setup on my side. I'll try to boot an older kernel from GRUB.

```
sander@witte2004:~/git/sockdump$ ll /var/run/docker.sock
srw-rw---- 1 root docker 0 dec 22 17:42 /var/run/docker.sock=
sander@witte2004:~/git/sockdump$ sudo ./sockdump.py --format string /var/run/docker.sock
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:304:4: error: use of undeclared identifier 'KBUILD_MODNAME'
                        NL_SET_ERR_MSG_MOD(extack, "Mixing HW stats types for actions is not supported");
                        ^
include/linux/netlink.h:96:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                 ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:304:4: error: expected ';' at end of declaration
include/linux/netlink.h:96:42: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                                ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:338:3: error: use of undeclared identifier 'KBUILD_MODNAME'
                NL_SET_ERR_MSG_MOD(extack, "Driver supports only default HW stats type \"any\"");
                ^
include/linux/netlink.h:96:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                 ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:338:3: error: expected ';' at end of declaration
include/linux/netlink.h:96:42: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                                ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:342:3: error: use of undeclared identifier 'KBUILD_MODNAME'
                NL_SET_ERR_MSG_MOD(extack, "Driver does not support selected HW stats type");
                ^
include/linux/netlink.h:96:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                 ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:342:3: error: expected ';' at end of declaration
include/linux/netlink.h:96:42: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                                ^
6 errors generated.
Traceback (most recent call last):
  File "./sockdump.py", line 306, in <module>
    main(args)
  File "./sockdump.py", line 254, in main
    b = BPF(text=text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
sander@witte2004:~/git/sockdump$ 


```

**Comment by sanderjo** [comment]
Booted into kernel 5.4, and no more errors.

Might be a problem with my setup (my installed bpftrace not up-to-date?), so I'm closing this issue
