### ISSUE TITLE
Tool fails to run on Kali

### ISSUE THREAD

**Issue by eranzim** [mechpen/sockdump#6]
Running on Kali 2020.4, I get:
```
modprobe: FATAL: Module kheaders not found in directory /lib/modules/5.9.0-kali1-amd64
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module) or installing the kernel development package for your running kernel version.
chdir(/lib/modules/5.9.0-kali1-amd64/build): No such file or directory
Traceback (most recent call last):
  File "./sockdump.py", line 313, in <module>
    main(args)
  File "./sockdump.py", line 261, in main
    b = BPF(text=text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

I ran the tool with: `sudo ./sockdump.py /path/to/sockfile.sock`
Python3 version: `Python 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]`

**Comment by mechpen** [comment]
Looks the kernel headers are missing.  Could you try install them.  The bpf code needs these header files to compile.

**Comment by eranzim** [comment]
How can I install them? I tried: `sudo apt install linux-headers-$(uname -r)`, but got errors:
```
E: Unable to locate package linux-headers-5.9.0-kali1-amd64
E: Couldn't find any package by glob 'linux-headers-5.9.0-kali1-amd64'
```

**Comment by mechpen** [comment]
I am not familiar with kali.  But it looks 5.9.0 is outdated in kali.  You may need to upgrade your kernel.
http://http.kali.org/pool/main/l/linux/

**Comment by eranzim** [comment]
I tried installing latest Ubuntu LTS (20.04.2.0 LTS), after installing everything I still get an error:
```
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:42:
In file included from include/net/netprio_cgroup.h:11:
In file included from include/linux/cgroup.h:28:
In file included from include/linux/cgroup-defs.h:22:
In file included from include/linux/bpf-cgroup.h:5:
include/linux/bpf.h:1128:21: error: field has incomplete type 'enum bpf_link_type'
        enum bpf_link_type type;
                           ^
include/linux/bpf.h:1128:7: note: forward declaration of 'enum bpf_link_type'
        enum bpf_link_type type;
             ^
include/linux/bpf.h:1148:17: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                              struct bpf_link_info *info);
                                     ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:315:4: error: use of undeclared identifier 'KBUILD_MODNAME'
                        NL_SET_ERR_MSG_MOD(extack, "Mixing HW stats types for actions is not supported");
                        ^
include/linux/netlink.h:96:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                 ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:315:4: error: expected ';' at end of declaration
include/linux/netlink.h:96:42: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                                ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:350:3: error: use of undeclared identifier 'KBUILD_MODNAME'
                NL_SET_ERR_MSG_MOD(extack, "Driver supports only default HW stats type \"any\"");
                ^
include/linux/netlink.h:96:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                 ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:350:3: error: expected ';' at end of declaration
include/linux/netlink.h:96:42: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                                ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:354:3: error: use of undeclared identifier 'KBUILD_MODNAME'
                NL_SET_ERR_MSG_MOD(extack, "Driver does not support selected HW stats type");
                ^
include/linux/netlink.h:96:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                 ^
In file included from /virtual/main.c:5:
In file included from include/net/af_unix.h:9:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:25:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:354:3: error: expected ';' at end of declaration
include/linux/netlink.h:96:42: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                                ^
1 warning and 7 errors generated.
Traceback (most recent call last):
  File "./sockdump.py", line 313, in <module>
    main(args)
  File "./sockdump.py", line 261, in main
    b = BPF(text=text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

**Comment by mechpen** [comment]
Could you verify you can run the python bcc examples?

**Comment by eranzim** [comment]
I think they are written for python2 (I had to explicitly run them with python3)... Tried running `hello_world.py`, it looks like it isn't doing anything (even with the x64 fix specified inside). Tried `networking/simple_tc.py` and `networking/tc_perf_event.py` - both can't find `pyroute2` module even though I pip-installed it. `tracing/bitehist.py` gave `Exception: Failed to attach BPF program b'kprobe__blk_account_io_completion' to kprobe b'blk_account_io_completion'`, but `tracing/strlen_count.py` seems to work.

Is sockdump supposed to support python3 on x64 VMs?

**Comment by realitix** [comment]
Hello,
I have the same problem on Ubuntu 20.04

**Comment by mechpen** [comment]
> Is sockdump supposed to support python3 on x64 VMs?

Yes.  It should work.  What is your os version? I could give it a try this weekend.

Will also try Ubuntu 20.04

**Comment by eranzim** [comment]
> > Is sockdump supposed to support python3 on x64 VMs?
> 
> Yes. It should work. What is your os version? I could give it a try this weekend.
> 
> Will also try Ubuntu 20.04

Ubuntu 20.04.2.0 LTS

**Comment by mechpen** [comment]
I just did a fresh install of Ubuntu 20.04.2 LTS, installed python3 bcc binding with: `apt install python3-bpfcc`, then
sockdump worked as expected.

Did you install the package `python3-bpfcc`?

**Comment by eranzim** [comment]
Yes (I got version `0.12.0-2`)... Did you do any installation actions besides `apt install python3-bpfcc`? Defined any environment variables? Ran any configuration scripts?

**Comment by mechpen** [comment]
> Yes (I got version `0.12.0-2`)... Did you do any installation actions besides `apt install python3-bpfcc`? Defined any environment variables? Ran any configuration scripts?

I have the same version of python3-bpfcc.

**Comment by salmon5** [comment]
I test ubuntu 20.04,
sudo apt update
sudo apt install linux-headers-$(uname -r)
sudo apt install bpfcc-tools
work very well,

please note,the bcc-tools version is 0.12,max support kernel version is 5.4

**Comment by salmon5** [comment]
https://github.com/iovisor/bcc/releases
kernel 5.9 need bcc 0.17,you need install bcc from source code
